services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "37027:27017" # use a different host port to avoid collisions
    volumes:
      - mongo_data_ci:/data/db
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  auth:
    build: ./auth
    env_file:
      - ./auth/.env
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_started
    networks:
      - app-network

  product:
    build: ./product
    env_file:
      - ./product/.env
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_started
    networks:
      - app-network

  order:
    build: ./order
    env_file:
      - ./order/.env
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_started
    networks:
      - app-network

  api-gateway:
    build: ./api-gateway
    ports:
      - "3003:3003"
    restart: unless-stopped
    depends_on:
      auth:
        condition: service_started
      product:
        condition: service_started
      order:
        condition: service_started
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data_ci:


