services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "37027:27017" # use a different host port to avoid collisions
    volumes:
      - mongo_data_ci:/data/db
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  auth:
    build: ./auth
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_started
    environment:
      # minimal defaults for CI
      MONGODB_AUTH_URI: mongodb://mongo:27017/auth_db
      JWT_SECRET: test-secret
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    networks:
      - app-network

  product:
    build: ./product
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_started
    environment:
      MONGODB_PRODUCT_URI: mongodb://mongo:27017/product_db
      JWT_SECRET: test-secret
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    networks:
      - app-network

  order:
    build: ./order
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_started
    environment:
      MONGODB_ORDER_URI: mongodb://mongo:27017/order_db
      JWT_SECRET: test-secret
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    networks:
      - app-network

  api-gateway:
    build: ./api-gateway
    ports:
      - "3003:3003"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data_ci:


